### ISSUE TITLE
dict_keys error.

### ISSUE THREAD

**Issue by ghost** [mcdulltii/obfDetect#2]
while using it against themida hanhelds , i got this : 

```
func_list = list(reversed(sorted_functions.keys()))[:bound] if partial else list(reversed(sorted_functions.keys()))
TypeError: 'dict_keys' object is not reversible
```

**Comment by mcdulltii** [comment]
Please provide further details accordingly:
- Describe the bug
- To Reproduce
- Additional context
- Example Project

**Comment by ghost** [comment]
if you want to reproduce the bugg , make a themida hello world sample from the BLACK SHARK vm . there is no additionnal informations , i'm on the 7.6.210427 .  i tested the original code on Ninja , it works great .

**Comment by 0xhicham** [comment]
> Control Flow Flattening
> NOTE: Functions are likely not flattened
> ================================================================================
> Cyclomatic Complexity
> Traceback (most recent call last):
>   File "C:/ida76sp1/plugins/obfDetect.py", line 33, in activate
>     detect.all_heur()
>   File "C:/ida76sp1/plugins\obfDetect\detect.py", line 6, in all_heur
>     find_complex_functions(partial=True)
>   File "C:/ida76sp1/plugins/obfDetect/obfuscation_detection/heuristics.py", line 53, in find_complex_functions
>     func_list = list(reversed(sorted_functions.keys()))[:bound] if partial else list(reversed(sorted_functions.keys()))
> TypeError: 'dict_keys' object is not reversible
